import Foundation

extension Notification.Name {
    static let vaporCopyOriginal = Notification.Name("vaporCopyOriginal")
    static let vaporCompressAndCopy = Notification.Name("vaporCompressAndCopy")
    static let vaporCopyAndClear = Notification.Name("vaporCopyAndClear")
    static let vaporShowHistory = Notification.Name("vaporShowHistory")
    static let vaporShowHelp = Notification.Name("vaporShowHelp")
    static let vaporChooseBrowserTarget = Notification.Name("vaporChooseBrowserTarget")
    /// Posted to send the current prompt text to the browser extension.
    static let vaporSendToBrowser = Notification.Name("vaporSendToBrowser")
    /// Posted when the local LLM is downloaded (e.g. during onboarding) so the main window can reload.
    static let vaporLLMDownloadCompleted = Notification.Name("vaporLLMDownloadCompleted")
    static let vaporInsertContextItem = Notification.Name("vaporInsertContextItem")
    static let vaporOpenContextItem = Notification.Name("vaporOpenContextItem")
    static let vaporFocusEditor = Notification.Name("vaporFocusEditor")
    static let vaporFocusPromptHistory = Notification.Name("vaporFocusPromptHistory")
    static let vaporFocusScreenshots = Notification.Name("vaporFocusScreenshots")
    static let vaporFocusContextTray = Notification.Name("vaporFocusContextTray")
    static let vaporFocusToolRail = Notification.Name("vaporFocusToolRail")
    static let vaporScreenshotMoveLeft = Notification.Name("vaporScreenshotMoveLeft")
    static let vaporScreenshotMoveRight = Notification.Name("vaporScreenshotMoveRight")
    static let vaporScreenshotInsertSelected = Notification.Name("vaporScreenshotInsertSelected")
    static let vaporPromptHistoryMoveLeft = Notification.Name("vaporPromptHistoryMoveLeft")
    static let vaporPromptHistoryMoveRight = Notification.Name("vaporPromptHistoryMoveRight")
    static let vaporPromptHistoryRestoreSelected = Notification.Name("vaporPromptHistoryRestoreSelected")
    static let vaporContextMoveUp = Notification.Name("vaporContextMoveUp")
    static let vaporContextMoveDown = Notification.Name("vaporContextMoveDown")
    static let vaporContextActivatePrimary = Notification.Name("vaporContextActivatePrimary")
    static let vaporContextActivateSecondary = Notification.Name("vaporContextActivateSecondary")
    static let vaporToolMoveUp = Notification.Name("vaporToolMoveUp")
    static let vaporToolMoveDown = Notification.Name("vaporToolMoveDown")
    static let vaporToolActivate = Notification.Name("vaporToolActivate")
    static let vaporShowOnboarding = Notification.Name("vaporShowOnboarding")
}
